### ISSUE TITLE
Change MQTT Default topic

### ISSUE THREAD

**Issue by IVI053** [dingo35/SmartEVSE-3.5#119]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Instead of SmartEVSE-xxxx it would be better practise to use SmartEVSE/xxxx as default topic for MQTT. This way one who owns multiple units can utilise MQTT wildcards.

**Describe alternatives you've considered**
None, as this is just a suggestion. Manual change is always possible.

**Comment by dingo35** [comment]
Interesting suggestion, I'll look if we can implement this without losing backwards compatability.

**Comment by dingo35** [comment]
Done in 
[989f5fb5dc.zip](https://github.com/user-attachments/files/17460036/989f5fb5dc.zip)
