### ISSUE TITLE
Clarify docs - MQTT current direction 

### ISSUE THREAD

**Issue by chylek** [dingo35/SmartEVSE-3.5#138]
Hi,
I'm using home assistant automation to send mqtt messages with current derived from my home's consumption as the Mains Meter current measurements. But I'm not sure sure whether positive values mean that the house is taking from grid (and negative values mean I'm producing electricity into the grid) or vice versa.
I see clarification for battery measurements, but I'm not sure how they apply to the mains meter.
Can you clarify? 
Thanks
Adam

**Comment by dingo35** [comment]
Positive value means you are importing current from the grid, negative means you are exporting (delivering) current to the grid.
