### ISSUE TITLE
building firmware with OCPP

### ISSUE THREAD

**Issue by XsniferX** [dingo35/SmartEVSE-3.5#141]
Hello, 

base on previous instructions, I'm trying to build the firmware in order to enable OCPP.

so i did :

- curl -fsSL -o get-platformio.py https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py
- sudo apt-get install python3.11-venv (i was asked to)
- python3 get-platformio.py

then : 

- edited : ~/.profile (root user)
- added "export PATH=$PATH:$HOME/.local/bin"
- mkdir /root/.local/bin
- added :
   - ln -s ~/.platformio/penv/bin/platformio ~/.local/bin/platformio
   - ln -s ~/.platformio/penv/bin/pio ~/.local/bin/pio
   - ln -s ~/.platformio/penv/bin/piodebuggdb ~/.local/bin/piodebuggdb

then : 

- cd /tmp
- copy the latest release and extracted in /tmp
- cd to "/tmp/SmartEVSE-3.5-3.6.10/SmartEVSE-3"
- ran "platformio run -e ocpp"

but with or without -e ocpp it always failing when it try to build the firmware :

`Compiling .pio/build/ocpp/FrameworkArduino/esp32-hal-uart.c.o
/root/.platformio/packages/framework-arduinoespressif32@3.20014.231204/cores/esp32/esp32-hal-uart.c: In function 'uartSetPins':
/root/.platformio/packages/framework-arduinoespressif32@3.20014.231204/cores/esp32/esp32-hal-uart.c:153:9: warning: 'return' with no value, in function returning non-void
         return;
         ^~~~~~
/root/.platformio/packages/framework-arduinoespressif32@3.20014.231204/cores/esp32/esp32-hal-uart.c:149:6: note: declared here
 bool uartSetPins(uint8_t uart_num, int8_t rxPin, int8_t txPin, int8_t ctsPin, int8_t rtsPin)
      ^~~~~~~~~~~
Compiling .pio/build/ocpp/FrameworkArduino/firmware_msc_fat.c.o
Compiling .pio/build/ocpp/FrameworkArduino/libb64/cdecode.c.o
Compiling .pio/build/ocpp/FrameworkArduino/libb64/cencode.c.o
Compiling .pio/build/ocpp/FrameworkArduino/main.cpp.o
Compiling .pio/build/ocpp/FrameworkArduino/stdlib_noniso.c.o
Compiling .pio/build/ocpp/FrameworkArduino/wiring_pulse.c.o
Compiling .pio/build/ocpp/FrameworkArduino/wiring_shift.c.o
Archiving .pio/build/ocpp/libFrameworkArduino.a
Linking .pio/build/ocpp/firmware.elf
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pio/build/ocpp/src/mongoose.c.o:(.literal.packed_open+0x0): undefined reference to `mg_unpack'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pio/build/ocpp/src/mongoose.c.o:(.literal.packed_stat+0x0): undefined reference to `mg_unlist'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pio/build/ocpp/src/mongoose.c.o: in function `packed_open':
/tmp/SmartEVSE-3.5-3.6.10/SmartEVSE-3/src/mongoose.c:1893: undefined reference to `mg_unpack'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pio/build/ocpp/src/mongoose.c.o: in function `packed_stat':
/tmp/SmartEVSE-3.5-3.6.10/SmartEVSE-3/src/mongoose.c:1863: undefined reference to `mg_unpack'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /tmp/SmartEVSE-3.5-3.6.10/SmartEVSE-3/src/mongoose.c:1865: undefined reference to `mg_unlist'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pio/build/ocpp/src/mongoose.c.o: in function `mg_unpacked':
/tmp/SmartEVSE-3.5-3.6.10/SmartEVSE-3/src/mongoose.c:1850: undefined reference to `mg_unpack'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pio/build/ocpp/src/mongoose.c.o: in function `packed_list':
/tmp/SmartEVSE-3.5-3.6.10/SmartEVSE-3/src/mongoose.c:1877: undefined reference to `mg_unlist'
collect2: error: ld returned 1 exit status
*** [.pio/build/ocpp/firmware.elf] Error 1
======================================================================================================= [FAILED] Took 194.59 seconds =======================================================================================================

Environment    Status    Duration
-------------  --------  ------------
ocpp           FAILED    00:03:14.592
================================================================================================== 1 failed, 0 succeeded in 00:03:14.592 ==================================================================================================
root@pve01-docker-vm:/tmp/SmartEVSE-3.5-3.6.10/SmartEVSE-3#
`

does someone have any clues ?

Regards,

**Comment by dingo35** [comment]
There seems to be a problem with your python configuration.

Probably easier to wait for v3.7.0, that has OCPP built in by default....
