### ISSUE TITLE
EVMeter power not inverted to positive/absolute when using InvEastron.

### ISSUE THREAD

**Issue by rjmgmt** [dingo35/SmartEVSE-3.5#145]
**Describe the bug**
When using the InvEastron, the power value is shown as positive/absolute value on the SmartEVSE display, however within the WebUI/API/HA-addon it's shown as a negative value. All other related values (energy, current) are positive.

**Upload your config**
{"version":"v3.7.1","serialnr":xxxx,"mode":"SMART","mode_id":3,"car_connected":false,"wifi":{"status":"WL_CONNECTED","ssid":"HKHQ Home","rssi":-35,"bssid":"BA:FB:E4:C1:E4:54"},"evse":{"temp":29,"temp_max":65,"connected":false,"access":true,"mode":1,"loadbl":0,"pwm":1024,"custombutton":false,"solar_stop_timer":0,"state":"Ready to Charge","state_id":0,"error":"None","error_id":0,"rfid":"Not Installed"},"settings":{"charge_current":0,"override_current":0,"current_min":6,"current_max":16,"current_main":25,"current_max_circuit":16,"current_max_sum_mains":0,"max_sum_mains_time":0,"solar_max_import":0,"solar_start_current":6,"solar_stop_time":15,"enable_C2":"Auto","mains_meter":"Sensorbox","starttime":0,"stoptime":0,"repeat":0},"mqtt":{"host":"","port":1883,"topic_prefix":"SmartEVSE-7556","username":"","password_set":false,"status":"Disconnected"},"ocpp":{"mode":"Disabled","backend_url":"","cb_id":"","auth_key":"","auto_auth":"Disabled","auto_auth_idtag":"","status":"Disconnected"},"home_battery":{"current":0,"last_update":0},"ev_meter":{"description":"InvEastrn","address":16,"import_active_power":0,"total_kwh":28.79999924,"charged_kwh":0,"currents":{"TOTAL":0,"L1":0,"L2":0,"L3":0},"import_active_energy":28.79999924,"export_active_energy":0},"mains_meter":{"import_active_energy":0,"export_active_energy":0},"phase_currents":{"TOTAL":12,"L1":2,"L2":19,"L3":-9,"last_data_update":1730124410,"original_data":{"TOTAL":12,"L1":2,"L2":19,"L3":-9}},"backlight":{"timer":0,"status":"OFF"},"color":{"off":{"R":0,"G":0,"B":0},"normal":{"R":0,"G":255,"B":0},"smart":{"R":0,"G":255,"B":0},"solar":{"R":255,"G":170,"B":0},"custom":{"R":0,"G":0,"B":255}}}

**Upload a debug log**
N/A

**To Reproduce**
Use an InvEastron as EVMeter, check power value.

**Expected behavior**
It should transform the value to a positive/absolute value.

**Screenshots**
![IMG_8307](https://github.com/user-attachments/assets/cafae5a8-459a-4df4-8d17-b1e6b820e0f9)

**Comment by dingo35** [comment]
I am currently in an area without 230V/50Hz, so I cannot test Eastron devices for the next 5 weeks; please be patient.

**Comment by PimDoos** [comment]
Just encountered the same behavior. Energy is displayed correctly, charge power is negative.

**Comment by dingo35** [comment]
I cannot reproduce this:
![Screenshot_20241220_172840_Firefox](https://github.com/user-attachments/assets/cf767a90-2b55-47ae-bfbd-c225169efd78)

(Note that this is a meter that is normally configured as Eastron, so it is correct that the registered totals are negative when InvEastron is configured).

You are aware that if you are feeding the Eastron from the top, you should configure "Eastron" , and ONLY if you feed the Eastron from below, you should configure InvEastron?

**Comment by rjmgmt** [comment]
It's doing the same thing as we speak:
<img width="594" alt="Screenshot 2024-12-20 at 17 40 51" src="https://github.com/user-attachments/assets/8cd17e9c-8b31-4c68-aa80-b473a6ace508" />

Raw data:
"ev_meter":{"description":"InvEastrn","address":16,"import_active_power":-10.30000019,"total_kwh":552.7000122,"charged_kwh":9.600000381,"currents":{"TOTAL":446,"L1":148,"L2":150,"L3":148},"import_active_energy":552.7000122,"export_active_energy":0},

And yes, i'm aware, it's fed from the bottom.

**Comment by PimDoos** [comment]
Yes, I am feeding the Eastron meter from below.
![image](https://github.com/user-attachments/assets/753fa98e-76a3-4dcb-a2e0-6d8cda2a7400)

When selecting 'Eastron' as the EV Meter, the value for charged energy and EV Power are displayed as negative when charging.
When selecting 'Inverted Eastron', only the charged energy value is inverted to positive. The power value stays negative.
I suspect the power value is not inverted when using the Inverted Eastron mode, as the meter itself also reads a negative value. I would expect this power value to be inverted by SmartEVSE.

**Comment by rjmgmt** [comment]
Similar set-up to Pim here and also the very same SDM630 modbus v2. 

![IMG_8363](https://github.com/user-attachments/assets/fe660a74-9933-40e2-9e35-c4c9069226e0)

**Comment by PimDoos** [comment]
I think this is the issue. Inverted Eastron meters power values are not inverted if the value reported is negative.
https://github.com/dingo35/SmartEVSE-3.5/blob/94ca08ef4b211b9c34717bbf46912cc2d5a77706/SmartEVSE-3/src/meter.cpp#L266

e.g. for read value of -2400 W this statement works out as follows:
-2400 is not greated than 0, so do not invert the power value.

**Comment by dingo35** [comment]
Ok Im testing at SDM72D-M v2 here, so that might explain the different outcomes...

Could you guys test v3.6.6,  there were some major changes the code between  v3.6.6 and v3.6.7 ?

**Comment by rjmgmt** [comment]
Just tried, but I can't seem to be able to downgrade to 3.6.6 through the UI from 3.7.2. The upload of firmware.bin just stops. 

I'll try again tomorrow.

**Comment by PimDoos** [comment]
Found the bug and got it working locally with the fix implemented. I'll open a PR to merge.
![image](https://github.com/user-attachments/assets/53bdc59b-4b86-4ad1-a6cb-e34fcc141a13)

**Comment by rjmgmt** [comment]
Thanks for the fix @PimDoos. I just tried to test with the old firmware again, but i guess the downgrade is too much of a step.
