### ISSUE TITLE
Master/slave not working in update 3.7.2

### ISSUE THREAD

**Issue by rvdgaag** [dingo35/SmartEVSE-3.5#151]
**Describe the bug**

Slave unit does report "communications error", all data is fed by the API to the Master (every 2 seconds) for the EV data and Mains data via MQTT and also the EV data for the slave is pushed via MQTT to the slave as well .

Reverting back to 3.7.1 all is well.

**Comment by jbah1** [comment]
Same issue here. slave stopped working on latest.

**Comment by dingo35** [comment]
Thanks for your report, this fix should solve it:
[1fdfdc0d.zip](https://github.com/user-attachments/files/17791644/1fdfdc0d.zip)
