### ISSUE TITLE
When setting "min current" in Solar mode, it affects Normal mode

### ISSUE THREAD

**Issue by zulufoxtrot** [dingo35/SmartEVSE-3.5#161]
**Describe the bug**

When setting too low of a minimum current (say, 4A), the car refuses to start charging. This is not really a problem, but it is how I discovered the bug, described below:
I suspect the setting is persisted across modes and somehow affects Normal mode, even though Normal mode does not support/offer a setting for min current.
Not a big deal but it took me a while to understand what was going on.

**Upload your config**
[settings.json](https://github.com/user-attachments/files/18067715/settings.json)

**Upload a debug log**

-

**To Reproduce**

1. Go into Solar mode
2. Set min current to 4A (I have compiled the firmware to go as low as 4A)
3. Go into Normal mode
4. Connect car

**Expected behavior**
SmartEVSE uses a "default" start current. Car starts charging.

**Actual behavior**
SmartEVSE uses 4A. Car won't start charging.

**Comment by dingo35** [comment]
This is exactly what the documentarion warns of: changing MIN CURRENT leads to unexpeted results since the standards do not support it. Hence we do not support it.

The only appropriate action would be to remove this compile option....
