### ISSUE TITLE
Does SmartEVSE support Easton 72M V2 Kwh meter?

### ISSUE THREAD

**Issue by rhannink** [dingo35/SmartEVSE-3.5#18]
Hello,

Can anyone conform that the Easton 72M v2 Modus Kwh meter is working with this firmware?

https://stromzähler.eu/media/5f/b6/aa/1696582672/sdm72dm-v2.pdf

Gr. Remco

**Comment by dingo35** [comment]
Yes Im using the SDM72D-M v2 so yours will work with the Eastron3p setting.

**Comment by rhannink** [comment]
One more question, if I connect the Easton via Modbus to the Smartevse, does the Home assistant integration report the ev_meter values back to Home Assistant? I like to sea the actual EV charge values and the KWH SUM for the EV both on the display of the Easton as well as in my HA dashboard. 

Gr. Remco

**Comment by dingo35** [comment]
Yes it will.
