### ISSUE TITLE
Smart EVSE is not booting

### ISSUE THREAD

**Issue by 2pjnl** [dingo35/SmartEVSE-3.5#19]
From the start I have had problems with stability and the Smart EVSE crashes regularly. After flashing Release v3.5.0-RC1, this seemed to go better. On my workbench it worked for a few hours without crashing. I then mounted it back in the enclosure and charging went well for a few hours until it crashed again. After a power cycle it would not start again, the screen only flashed once.

After disassembling and connecting via USB-C it would boot, but it crashed again after 9-10 seconds. Now it no longer boots via USB-C. I initially think of a software problem. Is it possible to flash it via USB-C?

**Comment by dingo35** [comment]
https://github.com/dingo35/SmartEVSE-3.5/blob/master/docs/configuration.md

Last paragraph, "building the firmware" tells you how to upload via USB-C

**Comment by dingo35** [comment]
If you're sure that COM3 is the right port, and you have a good USB cable, and it is plugged in correctly.... then I don't know what the problem is.....




"2pjnl" ***@***.***> schreef op 26 februari 2024 om 15:57:
