### ISSUE TITLE
MQTT Topic is replaced with default "SmartEVSE-xxxx" after reboot

### ISSUE THREAD

**Issue by Imaginous** [dingo35/SmartEVSE-3.5#29]
**Describe the bug**
I had the MQTT topic called "SmartEVSE".
In the last udpdate it whas changed to "SmartEVSE-xxxx"... but if you manually change the topic back to "SmartEVSE" in my case it works.

Until a reboot, then it's back to the default "SmartEVSE-xxxx".

**To Reproduce**
1. Change MQTT topic in settings to "SmartEVSE" (without quotes).
2. See it's broadcasting in the new topic.
3. Reboot.
4. It's back to the default "SmartEVSE-xxxx".

**Expected behavior**
Keep a changed topic name.

**Comment by dingo35** [comment]
Thx for the report, fixed in d792aade35c37a
