### ISSUE TITLE
Feature request: OTA Update

### ISSUE THREAD

**Issue by devdems** [dingo35/SmartEVSE-3.5#33]
Is there a plan to simplify the update process? While we programmers and a small percentage of other users can do this process without even thinking, it would be wise to have a more straightforward one-button update approach for the future.

**Comment by dingo35** [comment]
Yep, in fact working on it as we speak. v3.5.0 is on a freeze now so for one of the later releases

**Comment by dingo35** [comment]
Fixed in v.3.6.3
