### ISSUE TITLE
Feature request: New storage mode, for charging the car from the power storage without electricity from the grid

### ISSUE THREAD

**Issue by Elektrofix-OL** [dingo35/SmartEVSE-3.5#47]
**Is your feature request related to a problem? Please describe.**
I have a solar system with a large storage capacity of 28.8kWh. During the day, the solar system fully charges the battery; When I get home I just want to load the car from the memory.
- When I charge in solar mode, there isn't enough power to charge, and it's already in the evening when I get home.
- If I choose smart mode, the system draws electricity from the grid when consumption increases in the house.here!

**Describe the solution you'd like**
I would like to see an additional “storage” mode that works like solar mode, but includes the storage as a power source.
The SmartEVSE then has to know how much power (ampere) the storage inverter can provide and take this into account in the calculation in order to charge the car without drawing electricity from the grid.
It would also be really cool to switch from solar to storage using the button that switches between solar and smart

**Describe alternatives you've considered**
The first attempt was to use API to trick the EVSE into thinking that the network's current values ​​were close to maximum; Unfortunately, the EVE stopped charging before the power from the storage was used.
The second attempt was to manipulate the EVSE's current value into the storage using API. Although the car was charged with electricity from the storage system, electricity was also drawn from the grid.

**Comment by dingo35** [comment]
I think you can do all that already; look at  
https://github.com/dingo35/SmartEVSE-3.5/blob/master/docs/configuration.md

You can manipulate the charging behaviour of the SmartEVSE by feeding homeBatteryCurrent, positive or negative, through the REST API or via MQTT.
