### ISSUE TITLE
Cycling trough power share nodes triggers reboot

### ISSUE THREAD

**Issue by Imaginous** [dingo35/SmartEVSE-3.5#52]
**Describe the bug**
When you cycle trough all power share options on the display and go beyond the last or first the SmartEVSE reboots. 

Release V3.5.0

**Comment by dingo35** [comment]
Thx for the report; Yes when you go from Node to non-Node it reboots; fairly complex communication problem which only happens on configuration, which is probably a few times on the lifetime of the SmartEVSE...
So I hope you dont mind if we put our time in the outstanding feature requests?

**Comment by Imaginous** [comment]
I don't mind ;)

I don't even use it, but was just testing and accidentally ran into it.

**Comment by dingo35** [comment]
Thx!
