### ISSUE TITLE
Disable Home Assistant auto-discovery

### ISSUE THREAD

**Issue by ocaj-nl** [dingo35/SmartEVSE-3.5#6]
**Is your feature request related to a problem? Please describe.**
In environments where HomeAssistant is not used, it is not useful to keep sending the MQTT-broker with the auto-discovery information. 

**Describe the solution you'd like**
Would it be possible to enable/disable the HomeAssistant-autodiscovery feature in the configuration?

**Describe alternatives you've considered**
I did not find a possibility to stop SmartEVSE from sending the auto-discovery information

**Comment by dingo35** [comment]
The architecture of MQTT is that every device should publish all info it can, with subscribers deciding whether to subscribe or not.

MQQT is so light weight such a config option would offer no notionable advantages, both client side and server side. 
On the other hand, sny config option generates questions and misconfiguration problems...

So just enjoy your SmartEVSE and ignore those few extra bytes on your network...
