### ISSUE TITLE
Feature request: Socket lock in API

### ISSUE THREAD

**Issue by RogMoe** [dingo35/SmartEVSE-3.5#72]
**Is your feature request related to a problem? Please describe.**
Unattended cable can get unplugged

**Describe the solution you'd like**
Have access to the lock through API and get feedback on the lock status, possibly even have an override button on the internal webpage.

**Describe alternatives you've considered**
none

**Additional context**
If the car is connected in solarmode and waiting to charge, the cable is not locked. Some people have their EVSE located in a public spot, accessable by others. Having control over the lock would be a great feature.

**Comment by dingo35** [comment]
I understand your wish, but Im hesitant to develop stuff I cannot test.
Did you test the version in #59 ?

**Comment by RogMoe** [comment]
1547209e471.zip you mean?
Nope because didn;t want to interfere with someone else's request.
I don't use a timer-start.
I'm willing to test anything within 24hr if thats any help.

**Comment by dingo35** [comment]
Ok so with:
"If the car is connected in solarmode and waiting to charge, the cable is not locked." you didnt mean you were delayed charging?

**Comment by RogMoe** [comment]
Yes, didn't mean "delayed charging". I never used delayd charging, delayed as in using the timer function.
Waiting for the sun to come up is "delayed charging" too in a way ;-) I understand the misunderstanding.

You added a function that locks the cable while waiting for the timed charging to begin. I ask you to extend that function to SOLAR mode too.

**Comment by fluppie** [comment]
BTW not 100% related, but during some test I hear the EVSE's sending a open actuator to the motors when nothing is plugged in. Is that needed? Or is no one aware of this :)?

**Comment by dingo35** [comment]
I noficed this too a few days ago, I'll upload the fix.

**Comment by dingo35** [comment]
Different actuator behaviour since v.3.6.1
