### ISSUE TITLE
Mains Meter issues affect Normal charging, but config is hidden while in Normal charging mode

### ISSUE THREAD

**Issue by thmjanssen** [dingo35/SmartEVSE-3.5#80]
Bit of a corner case, but I ran into the following as I was swapping my mains meter hardware:

If you have the following setup:
- SmartEVSE in Smart/Solar Mode
- Mains Meter configured (in my case as API)

and then in either order:
- change charging mode to Normal
- break the Mains Meter feed to the SmartEVSE

the smartEVSE stops working with Communication Error as a result, but the Mains Meter setting is not visible in the Menu. If you want to remove the Mains Meter setting, you first need to switch back to Smart Mode, remove the Mains Meter setting and then switch back to normal.

Expected behaviour:
I would expect the SmartEVSE to "just" charge in Normal mode, and completely disregard if the Mains Meter feed is working or not. Maybe report the Mains Meter issue in the UI, but not block charging because of it.

**Comment by dingo35** [comment]
A lot of people use their SmartEVSE as a gateway from/to modbus and HomeAssistant, even in Normal mode

They hate having "blank" or incorrect values in their logs.

So you either configure a MainsMeter and provide the data, or you disable it.

We  made this behaviour on user request
 Ping ponging hence and forth between opposite use cases seems pointless....
