### ISSUE TITLE
Can't connect to webserver or API after update to 3.6.3

### ISSUE THREAD

**Issue by robbievlekken** [dingo35/SmartEVSE-3.5#96]
I've got two Smart EVSE controllers and updated one of them to version 3.6.3. The previous installed was 3.5.1.

I can't connect to the webserver anymore via browser or curl. I can still ping the controller however.

I saw there was a previous bug logged with the same issue, the issue was closed and mentioned that a fix was included in 3.6.2.

I'll try the method described in the other ticket to get my controller up and running again.

**Comment by dingo35** [comment]
Just disable and re-enable your wifi via the LCD screen, goto the /update screen, and update to v3.6.5 . It has improved wifi reconnection.
